app:
    resource: "@AppBundle/Controller/"
    type:     annotation

login:
    path:   /login
    defaults:  { _controller: AppBundle:Default:login }

login_check:
    path: /login_check

logout:
    path: /logout

inicio:
    path:   /inicio
    defaults:  { _controller: AppBundle:Inicio:inicio }

alta:
    path:   /alta
    defaults:  { _controller: AppBundle:Alta:alta }

altaedicion:
    path:   /altaedicion/{idactividad}
    defaults:  { _controller: AppBundle:Alta:altaedicion }

consulta_actividades:
    path:   /consulta_actividades
    defaults:  { _controller: AppBundle:Alta:consulta_actividades}

crear_actividades:
    path:   /crear_actividades
    defaults:  { _controller: AppBundle:Alta:crear_actividades }

gestionar:
    path:   /gestionar
    defaults:  { _controller: AppBundle:Gestionar:gestionar }

consultar:
    path:   /consultar
    defaults:  { _controller: AppBundle:Consultar:consultar }    




