<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Edicion extends \AppBundle\Entity\Edicion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Edicion' . "\0" . 'fechaEdicion', '' . "\0" . 'AppBundle\\Entity\\Edicion' . "\0" . 'autorizacion', '' . "\0" . 'AppBundle\\Entity\\Edicion' . "\0" . 'menoresEdad', '' . "\0" . 'AppBundle\\Entity\\Edicion' . "\0" . 'observaciones', '' . "\0" . 'AppBundle\\Entity\\Edicion' . "\0" . 'idciclo', '' . "\0" . 'AppBundle\\Entity\\Edicion' . "\0" . 'idedicion', '' . "\0" . 'AppBundle\\Entity\\Edicion' . "\0" . 'actividadactividad', '' . "\0" . 'AppBundle\\Entity\\Edicion' . "\0" . 'estadoestado'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Edicion' . "\0" . 'fechaEdicion', '' . "\0" . 'AppBundle\\Entity\\Edicion' . "\0" . 'autorizacion', '' . "\0" . 'AppBundle\\Entity\\Edicion' . "\0" . 'menoresEdad', '' . "\0" . 'AppBundle\\Entity\\Edicion' . "\0" . 'observaciones', '' . "\0" . 'AppBundle\\Entity\\Edicion' . "\0" . 'idciclo', '' . "\0" . 'AppBundle\\Entity\\Edicion' . "\0" . 'idedicion', '' . "\0" . 'AppBundle\\Entity\\Edicion' . "\0" . 'actividadactividad', '' . "\0" . 'AppBundle\\Entity\\Edicion' . "\0" . 'estadoestado'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Edicion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setFechaEdicion($fechaEdicion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaEdicion', [$fechaEdicion]);

        return parent::setFechaEdicion($fechaEdicion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaEdicion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaEdicion', []);

        return parent::getFechaEdicion();
    }

    /**
     * {@inheritDoc}
     */
    public function setAutorizacion($autorizacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAutorizacion', [$autorizacion]);

        return parent::setAutorizacion($autorizacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getAutorizacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAutorizacion', []);

        return parent::getAutorizacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setMenoresEdad($menoresEdad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMenoresEdad', [$menoresEdad]);

        return parent::setMenoresEdad($menoresEdad);
    }

    /**
     * {@inheritDoc}
     */
    public function getMenoresEdad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMenoresEdad', []);

        return parent::getMenoresEdad();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservaciones($observaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservaciones', [$observaciones]);

        return parent::setObservaciones($observaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservaciones', []);

        return parent::getObservaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdciclo($idciclo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdciclo', [$idciclo]);

        return parent::setIdciclo($idciclo);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdciclo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdciclo', []);

        return parent::getIdciclo();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdedicion()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdedicion();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdedicion', []);

        return parent::getIdedicion();
    }

    /**
     * {@inheritDoc}
     */
    public function setActividadactividad(\AppBundle\Entity\Actividad $actividadactividad = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActividadactividad', [$actividadactividad]);

        return parent::setActividadactividad($actividadactividad);
    }

    /**
     * {@inheritDoc}
     */
    public function getActividadactividad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActividadactividad', []);

        return parent::getActividadactividad();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstadoestado(\AppBundle\Entity\Estado $estadoestado = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadoestado', [$estadoestado]);

        return parent::setEstadoestado($estadoestado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadoestado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadoestado', []);

        return parent::getEstadoestado();
    }

}
