<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Evaluacion extends \AppBundle\Entity\Evaluacion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Evaluacion' . "\0" . 'objetivo', '' . "\0" . 'AppBundle\\Entity\\Evaluacion' . "\0" . 'duracion', '' . "\0" . 'AppBundle\\Entity\\Evaluacion' . "\0" . 'interesAlumno', '' . "\0" . 'AppBundle\\Entity\\Evaluacion' . "\0" . 'formaImpartir', '' . "\0" . 'AppBundle\\Entity\\Evaluacion' . "\0" . 'dinamicaGrupo', '' . "\0" . 'AppBundle\\Entity\\Evaluacion' . "\0" . 'material', '' . "\0" . 'AppBundle\\Entity\\Evaluacion' . "\0" . 'instalaciones', '' . "\0" . 'AppBundle\\Entity\\Evaluacion' . "\0" . 'opinionGeneral', '' . "\0" . 'AppBundle\\Entity\\Evaluacion' . "\0" . 'repetiria', '' . "\0" . 'AppBundle\\Entity\\Evaluacion' . "\0" . 'observaciones', '' . "\0" . 'AppBundle\\Entity\\Evaluacion' . "\0" . 'idevaluacion', '' . "\0" . 'AppBundle\\Entity\\Evaluacion' . "\0" . 'edicionedicion'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Evaluacion' . "\0" . 'objetivo', '' . "\0" . 'AppBundle\\Entity\\Evaluacion' . "\0" . 'duracion', '' . "\0" . 'AppBundle\\Entity\\Evaluacion' . "\0" . 'interesAlumno', '' . "\0" . 'AppBundle\\Entity\\Evaluacion' . "\0" . 'formaImpartir', '' . "\0" . 'AppBundle\\Entity\\Evaluacion' . "\0" . 'dinamicaGrupo', '' . "\0" . 'AppBundle\\Entity\\Evaluacion' . "\0" . 'material', '' . "\0" . 'AppBundle\\Entity\\Evaluacion' . "\0" . 'instalaciones', '' . "\0" . 'AppBundle\\Entity\\Evaluacion' . "\0" . 'opinionGeneral', '' . "\0" . 'AppBundle\\Entity\\Evaluacion' . "\0" . 'repetiria', '' . "\0" . 'AppBundle\\Entity\\Evaluacion' . "\0" . 'observaciones', '' . "\0" . 'AppBundle\\Entity\\Evaluacion' . "\0" . 'idevaluacion', '' . "\0" . 'AppBundle\\Entity\\Evaluacion' . "\0" . 'edicionedicion'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Evaluacion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setObjetivo($objetivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObjetivo', [$objetivo]);

        return parent::setObjetivo($objetivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getObjetivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObjetivo', []);

        return parent::getObjetivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setDuracion($duracion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDuracion', [$duracion]);

        return parent::setDuracion($duracion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDuracion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDuracion', []);

        return parent::getDuracion();
    }

    /**
     * {@inheritDoc}
     */
    public function setInteresAlumno($interesAlumno)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInteresAlumno', [$interesAlumno]);

        return parent::setInteresAlumno($interesAlumno);
    }

    /**
     * {@inheritDoc}
     */
    public function getInteresAlumno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInteresAlumno', []);

        return parent::getInteresAlumno();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormaImpartir($formaImpartir)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormaImpartir', [$formaImpartir]);

        return parent::setFormaImpartir($formaImpartir);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormaImpartir()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormaImpartir', []);

        return parent::getFormaImpartir();
    }

    /**
     * {@inheritDoc}
     */
    public function setDinamicaGrupo($dinamicaGrupo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDinamicaGrupo', [$dinamicaGrupo]);

        return parent::setDinamicaGrupo($dinamicaGrupo);
    }

    /**
     * {@inheritDoc}
     */
    public function getDinamicaGrupo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDinamicaGrupo', []);

        return parent::getDinamicaGrupo();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaterial($material)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaterial', [$material]);

        return parent::setMaterial($material);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaterial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaterial', []);

        return parent::getMaterial();
    }

    /**
     * {@inheritDoc}
     */
    public function setInstalaciones($instalaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInstalaciones', [$instalaciones]);

        return parent::setInstalaciones($instalaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getInstalaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInstalaciones', []);

        return parent::getInstalaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setOpinionGeneral($opinionGeneral)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpinionGeneral', [$opinionGeneral]);

        return parent::setOpinionGeneral($opinionGeneral);
    }

    /**
     * {@inheritDoc}
     */
    public function getOpinionGeneral()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpinionGeneral', []);

        return parent::getOpinionGeneral();
    }

    /**
     * {@inheritDoc}
     */
    public function setRepetiria($repetiria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRepetiria', [$repetiria]);

        return parent::setRepetiria($repetiria);
    }

    /**
     * {@inheritDoc}
     */
    public function getRepetiria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRepetiria', []);

        return parent::getRepetiria();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservaciones($observaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservaciones', [$observaciones]);

        return parent::setObservaciones($observaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservaciones', []);

        return parent::getObservaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdevaluacion()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdevaluacion();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdevaluacion', []);

        return parent::getIdevaluacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setEdicionedicion(\AppBundle\Entity\Edicion $edicionedicion = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEdicionedicion', [$edicionedicion]);

        return parent::setEdicionedicion($edicionedicion);
    }

    /**
     * {@inheritDoc}
     */
    public function getEdicionedicion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEdicionedicion', []);

        return parent::getEdicionedicion();
    }

}
